services:
  web:
    build:
      context: .
      dockerfile: ./infra/local/web/Dockerfile
    container_name: 'web'
    tty: true
    ports:
      - 8000:80
    environment:
      ACCESS_LOG_LOCATION: /var/log/nginx/access.log
      PROXY_PASS_HTTP: http://app:8000
  app:
    restart: always
    build:
      context: .
      dockerfile: ./infra/local/app/Dockerfile
    container_name: 'app'
    working_dir: '/usr/src/app'
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - 8080:8000
  db:
    image: mysql:8.0.35
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wakarunDB
      MYSQL_USER: wakarun
      MYSQL_PASSWORD: 2024autumn
    restart: always
    volumes:
      - ./infra/local/db_data:/var/lib/mysql
