# Generated by Django 5.1.2 on 2024-10-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
