# Generated by Django 5.1.2 on 2024-11-02 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_create_at_questions_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('user_icon', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='title',
            field=models.CharField(default='未設定', max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_true', models.BooleanField()),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='API.questions')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField()),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='API.questions')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='API.users')),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='API.users'),
        ),
    ]
