# Generated by Django 5.1.2 on 2024-10-27 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_users_remove_questions_user_id_questions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='API.users'),
        ),
    ]
