# Generated by Django 5.1.2 on 2024-11-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_customuser_alter_favorites_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
