# Generated by Django 5.1.2 on 2024-11-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_customuser_is_active_customuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
