# Generated by Django 5.1.2 on 2024-11-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_rename_create_at_customuser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
    ]
