# Generated by Django 5.1.2 on 2024-11-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answers',
            name='is_true',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
