# Generated by Django 5.1.2 on 2024-11-23 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_alter_answers_id_alter_answers_is_true_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
